# Jekyll 站点配置

collections:
  publications:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: detail
  - scope:
      path: ""
      type: "projects"
    values:
      layout: detail

exclude:
  - backups/
  - index_empty.html
  - portfolio-single-file.html
  - vendor/

markdown: kramdown
