# Jekyll 站点配置

title: 王晨 · 个人主页
description: 王晨的个人主页

url: ""
baseurl: ""

collections:
  publications:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: detail
  - scope:
      path: ""
      type: "projects"
    values:
      layout: detail

exclude:
  - backups/
  - index_empty.html
  - portfolio-single-file.html
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .nojekyll

markdown: kramdown
